import { JSONSchema } from 'objection';

export const TierConfigValidationSchema: JSONSchema = {
  type: 'object',
  required: [
    'tier_id',
    'country_id',
    'minimum_balance',
    'maximum_balance',
    'minimum_per_deposit',
    'maximum_per_deposit',
    'maximum_daily_deposit',
    'maximum_weekly_deposit',
    'maximum_monthly_deposit',
    'minimum_transaction_amount',
    'maximum_transaction_amount',
    'maximum_daily_transaction',
    'maximum_weekly_transaction',
    'maximum_monthly_transaction',
    'minimum_per_withdrawal',
    'maximum_per_withdrawal',
    'maximum_daily_withdrawal',
    'maximum_weekly_withdrawal',
    'maximum_monthly_withdrawal',
  ],
  properties: {
    id: { type: 'string' },
    tier_id: { type: 'string' },
    country_id: { type: 'string' },
    minimum_balance: { type: 'number' },
    maximum_balance: { type: 'number' },
    minimum_per_deposit: { type: 'number' },
    maximum_per_deposit: { type: 'number' },
    maximum_daily_deposit: { type: 'number' },
    maximum_weekly_deposit: { type: 'number' },
    maximum_monthly_deposit: { type: 'number' },
    minimum_transaction_amount: { type: 'number' },
    maximum_transaction_amount: { type: 'number' },
    maximum_daily_transaction: { type: 'number' },
    maximum_weekly_transaction: { type: 'number' },
    maximum_monthly_transaction: { type: 'number' },
    minimum_per_withdrawal: { type: 'number' },
    maximum_per_withdrawal: { type: 'number' },
    maximum_daily_withdrawal: { type: 'number' },
    maximum_weekly_withdrawal: { type: 'number' },
    maximum_monthly_withdrawal: { type: 'number' },

    // remittance
    remittance_minimum_per_deposit: { type: 'number' },
    remittance_maximum_per_deposit: { type: 'number' },
    remittance_maximum_daily_deposit: { type: 'number' },
    remittance_maximum_weekly_deposit: { type: 'number' },
    remittance_maximum_monthly_deposit: { type: 'number' },
    remittance_minimum_transaction_amount: { type: 'number' },
    remittance_maximum_transaction_amount: { type: 'number' },
    remittance_maximum_daily_transaction: { type: 'number' },
    remittance_maximum_weekly_transaction: { type: 'number' },
    remittance_maximum_monthly_transaction: { type: 'number' },
    remittance_minimum_per_withdrawal: { type: 'number' },
    remittance_maximum_per_withdrawal: { type: 'number' },
    remittance_maximum_daily_withdrawal: { type: 'number' },
    remittance_maximum_weekly_withdrawal: { type: 'number' },
    remittance_maximum_monthly_withdrawal: { type: 'number' },
    total_spendable: { type: 'number' },
    total_receivable: { type: 'number' },

    // pending transaction count limits (US users)
    maximum_pending_deposits_count: { type: 'integer' },
    maximum_pending_withdrawals_count: { type: 'integer' },

    // weekly transaction count limits (US users)
    maximum_weekly_deposit_count: { type: 'integer' },
    maximum_weekly_withdrawal_count: { type: 'integer' },
  },
};
